[workspace]
members = ["crates/arreat-core", "crates/arreat-app", "crates/arreat-data", "crates/arreat-market", "crates/arreat-static-mod"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.97.1"

[workspace.dependencies]
clap = { version = "4.5.46", features = ["derive"] }
csv = "1.3.1"
getrandom = "0.4.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.143", features = ["arbitrary_precision"] }
regex = "1.11.2"
reqwest = { version = "0.13", default-features = false, features = ["blocking", "json", "rustls"] }
rust_decimal = { version = "1.37.2", features = ["serde-with-str"] }
sha2 = "0.10.9"
tar = "0.4.44"
thiserror = "2.0.16"
