[package]
name = "arreat-market"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
arreat-data = { path = "../arreat-data" }
regex.workspace = true
reqwest.workspace = true
rust_decimal.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
